const data = 
[
    {
        "id": "1",
        "name": "ELLERY X M'O CAPSULE 1",
        "img": "./img/item__1.svg",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "52.00",
        "color": "blue",
        "size": "XXL",
        "quantity": "10",
    },
    {
        "id": "2",
        "name": "ELLERY X M'O CAPSULE 2",
        "img": "./img/item__2.svg",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "152.00",
        "color": "black",
        "size": "L",
        "quantity": "20",
    },
    {
        "id": "3",
        "name": "ELLERY X M'O CAPSULE 3",
        "img": "./img/item__3.svg",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "252.00",
        "color": "red",
        "size": "XL",
        "quantity": "30",
    },
    {
        "id": "4",
        "name": "ELLERY X M'O CAPSULE 4",
        "img": "./img/item__4.svg",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "352.00",
        "color": "yellow",
        "size": "M",
        "quantity": "40",
    },
    {
        "id": "5",
        "name": "ELLERY X M'O CAPSULE 5",
        "img": "./img/item__5.svg",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "452.00",
        "color": "white",
        "size": "S",
        "quantity": "50",
    },
    {
        "id": "6",
        "name": "ELLERY X M'O CAPSULE 6",
        "img": "./img/item__6.svg",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "price": "552.00",
        "color": "gray",
        "size": "XL",
        "quantity": "60",
    },
];
const productDataJson = JSON.stringify(data);
